### ISSUE TITLE
Thermal block level heating & cooling capacities? 

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#10]
Currently, heating and cooling capacities are attributes of HeatingVentilationAirConditioningSystem. Should these be moved to thermal block level? Otherwise we effectively assume that space conditioning category (conditioned/semiheated/unconditioned) is the same for all thermal blocks served by a given system, but this is not necessarily the case. This would affect zone conditioning category function that Xing is working on.

**Comment by supriyagoel** [comment]
@mkarpman Yes, I had this question as well. However, simulation tools dont necessarily report this information at thermal block/zone level.  For example, E+ does not attribute central plant energy consumption to individual zones. I think we will have to assume that the space conditioning catergory of a system applies to all zones served by that system.

**Comment by mkarpman** [comment]
For better or worse, we do include fields in the RMR that are not supported by some or any of the tools.  Lighting occupancy sensor type is a recent example. But aside from that, we currently have  the following relationships in the RMR:
- ThermalBlock has multiple Zones
- Zone has multiple Spaces
- Space has conditioning_type attribute that indicates whether it's "unconditioned" or "plenum" (among other options)
- ThermalBlock may be served by multiple HVAC systems (served_by_heating_ventilation_air_conditioning_systems)
- HVAC system may serve multiple Zones

In eQUEST, an HVAC system may serve conditioned spaces, plenum spaces and unconditioned spaces. So if we keep heating/cooling capacity at the system level only, we need to account for Space.conditioning_type (whether it's "unconditioned" or "plenum") in RMR capacity per unit area fields, and ensure that it's clear which area counts. I think we also need to update zone conditioning category function to account for that. Arghhh...

**Comment by JasonGlazer** [comment]
Should this still be open?

**Comment by JasonGlazer** [comment]
I think this is addressed by the heating and cooling capacity in Terminal

**Comment by mkarpman** [comment]
Yes, I agree
