### ISSUE TITLE
HVAC sytem to zone to thermal block relationship

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#13]
@JasonGlazer and @supriyagoel We currently have  the following relationships in the RMR:
- ThermalBlock has multiple Zones
- Zone has multiple Spaces
- ThermalBlock may be served by multiple HeatingVentilationAirConditioningSystem systems (served_by_heating_ventilation_air_conditioning_systems)
- HeatingVentilationAirConditioningSystem may serve multiple Zones

Perhaps the intent was to get rid of the ThermalBlock (or Zone?) so that we have either one or the other but not both?

Also, it doesn't seem right that HVAC system references zones, and ThermalBlock references HVAC systems. I think we need to align the references to have proper many-to-many relationship. (E.g., Zone can be served by multipl HVAC systems and each HVAC system can serve multiple zones).

**Comment by JasonGlazer** [comment]
I think we need to wait on this until we have test case descriptions on air side HVAC which should clarify what is required here.

**Comment by mkarpman** [comment]
Sounds good, but please keep this item open for now so that it doesn’t fall
through cracks.



*From:* Jason Glazer ***@***.***>
*Sent:* Thursday, July 15, 2021 12:24 PM
*To:* open229/ruleset-model-report-schema <
***@***.***>
*Cc:* mkarpman ***@***.***>; Author <
***@***.***>
*Subject:* Re: [open229/ruleset-model-report-schema] HVAC sytem to zone to
thermal block relationship (#13)



I think we need to wait on this until we have test case descriptions on air
side HVAC which should clarify what is required here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/open229/ruleset-model-report-schema/issues/13#issuecomment-880838572>,
or unsubscribe
