### ISSUE TITLE
Adding buildingsegment_open_schedule in removing building_open_schedule

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#22]
I suggest replacing building_open_schedule (attribute of building object) with a similar attribute at buildingsegment level. It will support the rules related to exterior lighting controls, and also for the interior lighting controls, specifically the requirement in 90.1 Table G3.1 #6 baseline column that says “Lighting shall be modeled having the automatic shutoff controls in buildings >5000 ft2”. It echoes 90.1 2004 Section 9.4.1.1 which said “Automatic Lighting Shutoff. Interior lighting in buildings larger than 5000 ft2 shall be controlled with an automatic control device to shut off building lighting in all spaces.” So during unoccupied hours, lighting schedules should be the same in the baseline and proposed design for buildings >5000 ft2

**Comment by JasonGlazer** [comment]
I think the current location of the attribute at the Building level makes sense and I'm not sure why it it would be at BuildingSegment.
