### ISSUE TITLE
Move is_all_new from building to buildingsegment

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#27]
With the current architecture, mixed use building would include one buildingsegment for each building area type. In addition, we have is_all_new attribute at the building level. So if a project involves a mixed use building office + retail, and office portion includes renovation and addition, then RMR would have to include two building objects: 
1. with is_all_new=false and single buildingsegment with area type = office 
2. with is_all_new=true and  two buildingsegments - one with area type = office and another with retail

Seems like it would be more efficient and intuitive to have is_all_new at the buildingsegment level. Then, the scenario above could be handled with one building object and three buildingsegment objects.

**Comment by JasonGlazer** [comment]
Moved is_all_new and change description and notes as appropriate.

    is_all_new:
      Description: "Indicates whether the building segment is completely new construction (true) or existing (false). "
      Data Type: "Boolean"
      Notes: "Projects that include additions should have a building segments that are existing (false) and for the addition (true). Curtain rules such as baseline fenestration area will apply differently to each portion."
