### ISSUE TITLE
Include additional details for infiltration modeling method

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#29]
App G has the following rule: "Infiltration shall be modeled using the same methodology and adjustments for weather and building operation in both the proposed design and the baseline building design." RMR has the following enumerations for InfiltrationMethodType: weather_driven, pressure_based, constant. Simulation tool may have multiple infiltration modeling methods that fall into given category (e.g., weather_driven). Suggest renaming infiltration:modeling_method to infiltration:modeling_method_type and adding infiltration:modeling_method_name attribute to ensure that the same method is used in the baseline and proposed.

**Comment by JasonGlazer** [comment]
Added:

    algorithm_name:
      Description: "Name of the algorithm used for modeling infiltration in the specific simulation engine."
      Data Type: "String"
