### ISSUE TITLE
infiltration pressure difference

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#30]
Currently, ASHRAE229:infiltration_pressure_difference allows any positive value. Since 90.1 prescribes leakage rates at 75Pa and provides the methodology to convert from the rate at 75Pa to the rate at wind pressure, we would need to either develop convertions for other pressure differentials OR only allow values of 75Pa and wind pressure. (Would 0 be entered for wind pressure?). I recommend making ASHRAE229:infiltration_pressure_difference an enumerated field with options of 75, 50 and 0.

**Comment by supriyagoel** [comment]
could instead make infiltration pressure difference a user specified value.

**Comment by mkarpman** [comment]
In order to verify that the leakage at the user-entered pressure differential is equivalent to App G-specified values at 75Pa, we'd need to come up with a conversion methodology other than what is provided in G3.1.1.4 (which would essentially be no longer applicable). To the best of my knowledge, blower door tests are tylically done at 75Pa for commercial and 50Pa for residential. We supported both of these in the 90.1 compliance form.

**Comment by JasonGlazer** [comment]
Added:

    infiltration_flow_rate:
      Description: "Design infiltration flow rate"
      Data Type: "Numeric"
      Range: ">=0"
      Units: "m3/s"
      Notes: "Infiltration flow rate for simulation infiltration models unadjusted for temperature difference or windspeed or schedule (may vary in meaning between simulation engines)."
