### ISSUE TITLE
Tracking whether the dynamic glazing is manual or automatic 

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#34]
90.1 App G has the following requirement for the Proposed Design: "Automatically controlled dynamic glazing may be modeled.
Manually controlled dynamic glazing shall use the average of the minimum and maximum SHGC and VT." We currently have subsurface:is_dynamic_glazing attribute, which does not allow differentiating between the manual and dynamic glazing. Suggest replacing it with  is_automatic_dynamic_glazing and is_manual_dynamic_glazing

**Comment by mkarpman** [comment]
Or we can keep it as is and just handle it as a manual check.

**Comment by JasonGlazer** [comment]
Added:

    dynamic_glazing_type:
      Description: "Type of dynamic glazing for the window subsurface"
      Data Type: "<SubsurfaceDynamicGlazingType>"
      Notes: "Indicates if the glazed subsurface can change it's performance properties and if it is automatic or not."

and:

SubsurfaceDynamicGlazingType:
  Object Type: "Enumeration"
  Enumerators:
    NOT_DYNAMIC:
      Description: "Not dynamic"
    MANUAL_DYNAMIC:
      Description: "Manual dynamic"
    AUTOMATIC_DYNAMIC:
      Description: "Automatic dynamic"
