### ISSUE TITLE
Question on fluid loops and external fluid loops

### ISSUE THREAD

**Issue by supriyagoel** [open229/ruleset-model-report-schema#36]
@JasonGlazer and @mkarpman - RMR has 'externalFluidLoop' and 'FluidLoop'. If i have to specify a purchased HW system with a pump, i would need to create an external fluid loop, a fluid loop and a pump. I would reference the fluid loop from the pump, and then reference the fluid loop from the external fluid loop.  I would also specify the pump W/GPM on the fluid loop. This seems a little convoluted where the only purpose the fluid loop is serving is to connect the pump to the external fluid loop. would it make sense to instead a reference to thee external fluid loop within the pump object ?

**Comment by JasonGlazer** [comment]
@supriyagoel You would need to specify a ExternalFluidSource (not loop) and a FluidLoop and a Pump. The ExternalFluidSource and the Pump would reference the FluidLoop in the Loop date element. The ExternalFluidSource would use a energy_source_type of either HOT_WATER or STEAM. Also remember that most of the FluidLoop parameters are actually located in FluidLoopDesignAndControl now.

**Comment by mkarpman** [comment]
@supriyagoel, since the relationships between different HVAC-related objects is still in flux, perhaps it makes sense to wait with developing the relevant TCDs till this is finalized?

**Comment by JasonGlazer** [comment]
I think the water side HVAC (FluidLoop, FluidLoopDesignAndControl, Boiler, Chiller, Pump, ExternalFluidSource, and the validation point groups) has all been approved the Schema WG and should be solid. It is the air-side that has not been decided.

**Comment by mkarpman** [comment]
I think the HVAC architecture that Tim has proposed touches both air-side and water-side. I looked at the minutes from the HVAC-related discussion at the last call, and seems that there was a talk about deciding on the over-arching philosophy?

**Comment by supriyagoel** [comment]
@JasonGlazer yes, what you've explained makes sense.
@mkarpman i believe the new discussion would change how a fluidloop is referenced by a HVAC system but shouldn't change the overall architecture of the fluidloop/pump/boiler/chiller. That part makes sense to me. I would've also liked to wait so that we dont have to redo the TCDs but the airside discussion might take 6-8 weeks to finalize and we need to work on these for RDS + Rule Tests.
