### ISSUE TITLE
SubsurfaceSubclassification does not support mapping to 90.1 Appendix G requirements

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#38]
App G prescribes baseline U-factor for swining and non-swinging doors. Suggest removing the additional door descriptors in subsurface.subclassification that are not relevant to App G as they unnecessarily complicate the mapping.

**Comment by JasonGlazer** [comment]
Table G3.1 part 5b says "Opaque door types shall be of the same type of construction as the proposed design and conform to the U-factor requirements from the same tables (A7)." which lists more door types. Plus spandrel and glass blocks are included since a subsurface is not just a door now.
