### ISSUE TITLE
DHW heater efficiency

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#40]
There is currently a single heater_efficiency input, which is insufficient to describe performance of DHW heater and verify its alignment with App G requirements. Suggest adding the following:
efficiency_metric
output_validation_points
standby_loss
integrated_storage_volume 

Also, I think we need Qty field in case there are multiple heaters that are the same, and also either a new object or additional fields for external storage tanks.

**Comment by JasonGlazer** [comment]
I addressed everything but Qty in the latest update. I don't believe we have used quantities for any other data group.
