### ISSUE TITLE
Zone.exhaust_airflow_rate does not have operating schedule for Rule 23-3

### ISSUE THREAD

**Issue by xingcx** [open229/ruleset-model-report-schema#47]
For Rule 23-3 "Baseline systems 5 & 7 serving lab spaces per G3.1.1c shall reduce lab exhaust and makeup air during unoccupied periods to 50% of zone peak airflow, the minimum outdoor airflow, or rate required to comply with minimum accreditation standards whichever is larger.", it seems that we need to check hourly exhaust airflow rate. But I was not able to find operating schedule for exhaust in the current schema version 0.0.3 under Zone, or FanSystem, or Fan.

**Comment by JasonGlazer** [comment]
Added "exhaust_schedule" in FanSystem for upcoming schema version 0.0.5
