### ISSUE TITLE
Fan power box control sequence for Rule 23-4

### ISSUE THREAD

**Issue by xingcx** [open229/ruleset-model-report-schema#48]
For Rule 23-4, "For baseline systems 6 and 8, Fans in parallel VAV fan-powered boxes shall run as the first stage of heating before the reheat coil is energized.", I was not able to find element associated with this type of control in the schema.

**Comment by JasonGlazer** [comment]
This is very specific requirement, what data elements would you suggest to capture this?

**Comment by JasonGlazer** [comment]
For 0.0.6, I am adding to the Terminal data group a data element:

```
    is_fan_first_stage_heat:
      Description: "True if the the fan is run as the first stage of heating before reheat coil."
      Data Type: "Boolean"
```
