### ISSUE TITLE
Request data element for energy source for heating system

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-report-schema#51]
For rule "Baseline HVAC systems using fossil fuel shall be modeled using natural gas. Except where natural gas is not available for the proposed building site, propane shall be used as the heating fuel."

There are energy source elements for misc equipment, boilers, chillers, external fluid source, SWH heating.  Please add fuel sources for heatingsystem.

**Comment by JasonGlazer** [comment]
I added the data element energy_source_type with the same EnergySourceTypeOptions enumeration as other locations. This will appear in the 0.0.5 schema. It does seem like there is some redundancy now with HeatingSystemType.
