### ISSUE TITLE
Request data element for building peak cooling load

### ISSUE THREAD

**Issue by xingcx** [open229/ruleset-model-report-schema#54]
For Rule 22-22, Section G3.1.3.7, "The baseline building design’s chiller plant shall be modeled with chillers having the number and type as indicated in Table G3.1.3.7 as a function of building peak cooling load."

**Comment by JasonGlazer** [comment]
Thanks @xingcx, I think we have a few different routes provide this. We could just assume that the sum of the CoolingSystem:total_cool_capacity could be a proxy for the building peak cooling loads. It is not necessarily coincident but it would probably be close. We could also add something to CoolingSystem that would be the peak cooling load a the time of the building peak cooling load or we could simply add to Building or BuildingSegment a peak cooling load. I'm not sure what it the best way to go. @supriyagoel @mcneillj @mkarpman do you have any guidance or other approaches?

**Comment by xingcx** [comment]
As discussed on RDS call, we will assume building_peak_cooling_load in the output data group for now and revisit this later.

**Comment by mkarpman** [comment]
That looks like good idea
