### ISSUE TITLE
Add new data elements to 'Fan' data group

### ISSUE THREAD

**Issue by supriyagoel** [open229/ruleset-model-report-schema#56]
Need the following data groups for the following rules

- 23-13, "System 11 Fan volume shall be reset form 100% airflow at 100% load to minimum airflow at 50% load.”
FractionDesignLoadat100pctDesignAirflow and FractionDesignLoadatMinAirflow

- 23-14, "System 11 Supply air temperature shall be reset from minimum supply air temp at 50% cooling load to room temp at 0% cooling load.”
SupplyAirTempAt50pctCoolingLoad, - SupplyAirTempAt0pctCoolingLoad, 

- 23-15, "System 11 in heating mode SAT shall be modulated to maintain space temp and airflow shall be fixed at minimum airflow.”
SupplyAirflowDuringHeatingMode SupplyAirTemperatureDuringHeatingMode

**Comment by JasonGlazer** [comment]
@supriyagoel several of these seem really 90.1 specific. I also wonder if they belong in FanSystem instead of Fan. Maybe we should add a data group for reset strategies that has more generic fields. This is a complex one. @mkarpman @mcneillj @xingcx do you have any suggestions.

**Comment by mkarpman** [comment]
@JasonGlazer and @supriyagoel , few thoughts on this:
1. It seems that the flow control attribute that we are discussing here should apply to the same data element as the existing FanSystem.temperature_control attribute. Both should either be at the Fan level or FanSystem level.
2. I think we need to add the following attributes to either Fan or FanSystem (per above):
- flow_control (analogous to existing temperature_control)
- maximum_load (not sure we need this)
- airflow_fraction_of_design_at_maximum_load
- airflow_fraction_of_design_at_minimum_load
3. I think we also need to add an attribute to describe reset priority to support rule 23-15- i.e., airflow_first, temperature_first and simultaneous

**Comment by JasonGlazer** [comment]
The exact text this is needed for is in Appendix G:

> G3.1.3.17 System 11 Supply Air Temperature and Fan Control
> 
> Minimum volume set point shall be 50% of the maximum design airflow rate, the minimum ventilation outdoor airflow rate, or the airflow rate required to comply with applicable codes or accreditation standards, whichever is larger. 
> 
> Fan volume shall be reset from 100% airflow at 100% cooling load to minimum air-flow at 50% cooling load. Supply air temperature set point shall be reset from minimum supply air temperature at 50% cooling load and above to space temperature at 0% cooling load. In heating mode supply air temperature shall be modulated to maintain space temperature, and fan volume shall be fixed at the minimum airflow.

**Comment by JasonGlazer** [comment]
Issues addressed in 0.0.6
