### ISSUE TITLE
Add new zone level data element for zone_floor_number

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-report-schema#58]
Can a new data element be added at the zone level for floor number, "zone_floor_number". Thank you.

Sure, its to assess G3.1.1 c, we need to be able to determine which system 5,6,7,8,9,10,11,12, or 13 a system 3 or 4 would have been part of where the zone met exception c . I think we can do this by knowing the floor that each zone is associated with for systems 5-8. @supriyagoel @mkarpman @JasonGlazer  However, this would not necesarily be the case for systems 9-13, does the team have any suggestions for how to handle these single zone systems? The wording of G3.1.1 c refers to spaces so even though 9-13 are single zone units there could be spaces that meet the criterual in G3.1.1 c.

**Comment by JasonGlazer** [comment]
@claperle for reference, can you provide the section number of Appendix G and quote the language from it that that needs this data element. It makes it easier to understand now and later why we are adding it.

**Comment by JasonGlazer** [comment]
Added in 0.0.6 to Zone data group

```
    floor_number
      Description: "Floor number"
      Data Type: "Numeric"
      Notes: "Used to group zones on a floor so the number indicates that different zones share a floor. The number should increase for increasing heights and be negative values for stories generally below ground and should generally correspond to numbering of floors on the plans. JG to verify if used in test case description."
```
