### ISSUE TITLE
Floor multiplier

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#59]
Section G3.1.1 a(4) says that "Floors with identical thermal blocks can be grouped for modeling purposes."

Table G3.1 #7 also says "Exceptions: Different HVAC zones may be combined to create a single thermal block or identical thermal blocks to which multipliers are applied, provided that all of the following conditions are met:....."

Should we add zone.multiplier to accommodate that? Or should BEM tools be required to "expand" any multipliers that were used in the model so that each zone is explicitly included in the RMR? The latter will avoid a conflict with Zone.floor field if multiplier is applied to represent zones on different floors. 

If Zone.multiplier attribute is added, we need to also think through how it affects parent HVAC systems.  

@supriyagoel please chime in also.

**Comment by JasonGlazer** [comment]
At this point, I think we should just assume that BEM tools expand any multipliers they use so that the Zone.floor data element continues to make sense.

**Comment by mkarpman** [comment]
That sounds good, but I think an appropriate note should be included into the RMR.

**Comment by JasonGlazer** [comment]
Even though I thought it existed, we don't have a Zone.floor data element. @mkarpman do you recall any previous discussion by the Schema WG on that?

**Comment by mkarpman** [comment]
Adding floor is included in issue #57

**Comment by JasonGlazer** [comment]
Yes, I just realized that and added it.
