### ISSUE TITLE
Field fixes from Karpman

### ISSUE THREAD

**Issue by JasonGlazer** [open229/ruleset-model-report-schema#6]
- HeatingVentilationAirConditioningSystem: change simulation_result_sensible_cool_capacity and simulation_result_heat_capacity to just sensible_cool_capacity and heat_capacity. These field applies to both baseline and proposed, and for the proposed modeled capacities must be as specified
- Surface: change adjacent_space_id to adjacent_zone_id, for consistency with surfaces being attributes of zones instead of spaces.

**Comment by JasonGlazer** [comment]
Fixed both issues with June 30 update to schema

**Comment by JasonGlazer** [comment]
Thanks @mkarpman

**Comment by mkarpman** [comment]
@JasonGlazer I am updating envelope TCDs to capture changes to the rules and schema, and have a few comments on the schema:

ASHRAE229
-	What’s the relationship between “schedules” listed here and schedules included in objects like lighting, occupancy, etc.? Perhaps remove these from here?
-	“building_rotation_angles” is a little confusing. Each surface has azimuth, which defines the actual exposure. So for App G, do we expect to see either “0” (building was not rotated) or “0, 90, 180, 270” (building was rotated), and any other input would be wrong?  
-	It’s not clear what “conditioning_components” mean. The Notes field seems to repeat the string from the row above. 

Building:  
-	It seems that the following elements should be moved from building to building segment:  number_of_floors, elevators, refrigeration_components, open_time and close_time
-  Suggest to replaced open_time and close_time with hourly schedules as these may vary by day of the week and seasons (e.g. for a school). Or maybe remove it altogether? This is a useful info, but not something that is captured in the model outside of the operating schedules assigned to particular component - e.g. occupancy or HVAC. 
 - suggest to move compliance_path to ASRHAE229?

Zone:
-	description for “infiltration” should be changed to “air leakage into the space zone” 

Other:
-	Schedule naming appear inconsistent – e.g., under Space, we have occupant_multiplier_schedule_name, and under infiltration we have multiplier_schedule_name. Should we always include “scheduled” object in the name, e.g. change to infiltration_multiplier_schedule_name

**Comment by JasonGlazer** [comment]
> 
> 
> @JasonGlazer I am updating envelope TCDs to capture changes to the rules and schema, and have a few comments on the schema:
> 
> ASHRAE229

First off, please keep in mind that no one has approved this data group yet. I have put stuff in it that seems appropriate but it still may change in the future.

> 
>     * What’s the relationship between “schedules” listed here and schedules included in objects like lighting, occupancy, etc.? Perhaps remove these from here?

In the hierarchical structure of a file, the schedules would all be shown below this point. Other places in the schema, the individual references to schedules would point to one of these. The reason to do this is that many times schedules are identical across zones or equipment.

> 
>     * “building_rotation_angles” is a little confusing. Each surface has azimuth, which defines the actual exposure. So for App G, do we expect to see either “0” (building was not rotated) or “0, 90, 180, 270” (building was rotated), and any other input would be wrong?

Yes, exactly. 

> 
>     * It’s not clear what “conditioning_components” mean. The Notes field seems to repeat the string from the row above.

You are correct the note is wrong. The "data type" shows that it is a list that can contain all the HVAC primary components (so far) and serves as how they are stored in the RMR file. The other places where these are referenced would just show their name (or ID).

> 
> 
> Building:

Again, please keep in mind that no one has approved this data group yet. I have put stuff in it that seems appropriate but it still may change in the future.

> 
>     * It seems that the following elements should be moved from building to building segment:  number_of_floors, elevators, refrigeration_components, open_time and close_time

Maybe. 

> 
>     * Suggest to replaced open_time and close_time with hourly schedules as these may vary by day of the week and seasons (e.g. for a school). Or maybe remove it altogether? This is a useful info, but not something that is captured in the model outside of the operating schedules assigned to particular component - e.g. occupancy or HVAC.

Some rule needed these, maybe for lighting on exterior signs. 


> 
>     * suggest to move compliance_path to ASRHAE229?

That makes sense

> 
> 
> Zone:
> 
>     * description for “infiltration” should be changed to “air leakage into the space zone”

You mean "air leakage into the zone" I assume, good catch.

> 
> 
> Other:
> 
>     * Schedule naming appear inconsistent – e.g., under Space, we have occupant_multiplier_schedule_name, and under infiltration we have multiplier_schedule_name. Should we always include “scheduled” object in the name, e.g. change to infiltration_multiplier_schedule_name

For Infiltration, I assumed there was not going to be another schedule and it would be obvious what was being multiplied but in Space it needs to be more specific. Does that make sense?

**Comment by JasonGlazer** [comment]
I just added issues #7, #8, #9 to address some of these issues
