### ISSUE TITLE
Request to change or add data element in FluidLoop.FluidLoopDesignAndControl

### ISSUE THREAD

**Issue by xingcx** [open229/ruleset-model-report-schema#60]
For Rule 22-6, "CHW Loop Max reset Temp is 54F when chilled water loop temperature reset type is load reset."

Team proposed to either add another pair of max and min temperatures to FluidLoopDesignAndControl or rename loop_supply_temperature_at_outdoor_high to min_loop_supply_temperature and loop_supply_temperature_at_outdoor_low to max_loop_supply_temperature.

**Comment by JasonGlazer** [comment]
To address this, added a new field in 0.0.6

```
    loop_supply_temperature_at_low_load:
      Description: "Loop supply temperature at low load"
      Data Type: "Numeric"
      Units: "C"
      Notes: "Used when temperature_reset_type = LOAD_RESET"

```
