### ISSUE TITLE
Include additional SWH types

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#62]
I suggest adding additional options under ServiceWaterHeaterType as follows:
1. Combination space service water heating boiler
2. Storage
3. Instantaneous
4. Boiler
5. Purchased heat

**Comment by JasonGlazer** [comment]
@mkarpman to differentiate between storage and instantaneous, the size of the Tank being referenced in the ServiceWaterHeatingEquipment should be sufficient. The other three options would require all sorts of other inputs or connections that we don't have currently ("boiler" for example would probably need to be part of a new fluid loop with a boiler and pump). We could add them but I want to make sure we need to. What requirement in 90.1 appendix G, RESNET, or Title 24 are we not capturing with the current schema?

**Comment by mkarpman** [comment]
The tank volume threshold seems to vary depending on heater type and fuel, is not consistently provided in 90.1 Table 7.8 and sometimes a bit confusing - e.g, for gas and electric instantaneous water heater, there is a category for storage capacity >=10 gal.

Section G1.2.1 requires that proposed design meets Section 7.2.1, which references Table 7.8. In that table, efficiency requirements are based on heater type, input capacity, recovery efficiency, storage capacity and some other factors, depending on heater type. So in order to verify that efficiency of the proposed heater meet the minimum required in Table 7.8.  

Combination space/SWH are mentioned in Table G3.1 #11:in Table 7.8 

Combination space/SWH are mentioned in Table G3.1 #11:
e. Where a combined system has been specified to meet both space heating and service water-heating loads, the proposed
design shall reflect the actual system type using actual component capacities and efficiencies.


e. Where a combined system has been specified to meet both space heating and service water-heating loads, the proposed
design shall reflect the actual system type using actual component capacities and efficiencies.

**Comment by JasonGlazer** [comment]
I still think the tank volume should be used to determine if instantaneous or storage otherwise would just need to confirm that the right type is being specified here anyway. 

Added HEAT_FROM_HOT_WATER_LOOP and COMBINATION_SERVICE_AND_SPACE to ServiceWaterHeaterType and hot_water_loop to ServiceWaterHeatingEquipment which I think should address the rest of the request.

Addressed in 0.0.8

**Comment by mkarpman** [comment]
Sounds good. We may revisit this once we start developing RDSs and TCDs for SWH to see if an additional field is necessary.
