### ISSUE TITLE
Capturing scheduled loop operation

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#64]
Currently, enumerations for fluidloop.operatoin includes continuous and intermittent. Suggest to add "scheduled". For example, should PTAC heating loop run through the summer?

**Comment by JasonGlazer** [comment]
@mkarpman what requirement in Appendix G or another standard describes this?

**Comment by mkarpman** [comment]
This may come into play if proposed design is served by PTAC where heating loop is shut off during part of the year (e.g., over the summer), or where proposed design has two-pipe loop with a scheduled switch-over from heating to cooling. Then, the baseline would have to be modeled with the same loop schedule as proposed, and the "scheduled" enumeration would support this. 

As a side note, we already have "scheduled" enumeration for EnergyRecoveryOperation and FanSysteTemperatureControlType. 

Also, perhaps we may consider replacing "intermittent" with "on-demand" as it seems clearer to me, but no strong feelings.

**Comment by JasonGlazer** [comment]
Added in 0.0.06
