### ISSUE TITLE
DCV

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#68]
There is currently no means in the schema to describe DCV. There is DemandControlVentilationControlType enumeration, but it doesn't seem to be reference by any data elements. I suggest the following updates to address that:
1. Add FanSystem.DemandControlVentilationControlType, to describe control at the HVAC system level
2. Add Zone.has_DCV (boolean) to address scenarios where the proposed system has DOAS with DCV in some zones but not others. This was recommended at one of the RDS calls.

**Comment by JasonGlazer** [comment]
Could you explain the zone.has_DCV boolean some more? I usually think of DCV as just adjusting the outdoor air damper on the AHU so it impacts all zones the same. The sensors for DCV are sometimes in a critical zone, is that what you meant?

**Comment by mkarpman** [comment]
This may apply to a multi-zone DOAS - for example, terminals providing OA to corridors will not have DCV but terminals providing OA to classrooms will.

**Comment by JasonGlazer** [comment]
Would this make more sense in the Terminal data group?

**Comment by mkarpman** [comment]
Yes, I think you are right.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.8 schema
