### ISSUE TITLE
Capturing terminal-level heating and cooling

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#69]
The current attributes of Terminal data object do not support systems like chilled beams, and it is unclear whether heat_capacity field applies to just radiant systems or also reheat. Per RDS call on 1/18, recommend making the following changes to Therminal data element:
1. Rename reheat_source to heat_source. The attribute will be used for zonal components of central HVAC systems including VAV reheat or heating side of chilled beams.  
2. Rename reheat_from_loop to heat_from_loop
3. Update notes to heat_capacity to indicate that it applies to onal heating component described under heat_source; change ReheatSourceType to HeatSourceType.
4. Add a trio of corresponding cooling fields including cool_source, cool_from_loop and cool_capacity. 
    Suggested enumerations for cool_source are chilled_water, none, other.

**Comment by JasonGlazer** [comment]
Addressed in 0.0.8
