### ISSUE TITLE
"OTHER" is not one of the enumeration values for VerticalFenestrationBuildingAreaType2019ASHRAE901. 

### ISSUE THREAD

**Issue by vijayvardhan94** [open229/ruleset-model-report-schema#72]
https://github.com/open229/ruleset-model-report-schema/blob/2fb7478bcf6b081b9bf23e50bb6a0219341981d9/docs229/Enumerations2019ASHRAE901.schema.json#L905

**Comment by JasonGlazer** [comment]
Addressed in 0.0.8
