### ISSUE TITLE
Data elements "AppG Used by TCDs" Recommend Set to TRUE R0

### ISSUE THREAD

**Issue by claperle** [open229/ruleset-model-report-schema#73]
Hi Maria,

The following data elements are used in the RDSs and are set to FALSE or Unknown for the "AppG Used by TCDs" field. Recommend they be switched to TRUE.

HeatingVentilationAirConditioningSystem-->FanSystem--> operation_during_occupied
HeatingVentilationAirConditioningSystem-->FanSystem--> minimum_outdoor_airflow
Zone-->terminals
Terminal--> heat_capacity
Terminal-->served_by_heating_ventilation_air_conditioning_systems
HeatingVentilationAirConditioningSystem-->preheat_systems
HeatingVentilationAirConditioningSystem-->FanSystem--> operation_during_unoccupied
Zone-->floor_number
HeatingVentilationAirConditioningSystem-->heating_systems-->energy_source_type
HeatingVentilationAirConditioningSystem-->FanSystem
HeatingVentilationAirConditioningSystem-->FanSystem-->ID
HeatingVentilationAirConditioningSystem-->FanSystem-->Operating_schedule

**Comment by mkarpman** [comment]
Christina, I made all the updates above.
