### ISSUE TITLE
Request to data element to associate pump with chiller. 

### ISSUE THREAD

**Issue by xingcx** [open229/ruleset-model-report-schema#84]
For Rule 22-24, "Each baseline chiller shall be modeled with separate chilled water pump interlocked to operate with the associated chiller."

It seems the current schema does not support checking if a pump is interlocked to operate with the associated chiller. Pump is associated with FluidLoop and multiple chillers might be on the same loop in either parallel or series configuration. 

One option is to add a data field (e.g. equipment_control) for Pump for its associated chiller (or chiller and its associated pump). Or we can simply request manual check for this rule.

**Comment by JasonGlazer** [comment]
Added "is_chilled_water_pump_interlocked" and "is_condenser_water_pump_interlocked" to Chiller data group to address this.
"
