### ISSUE TITLE
ServiceWaterHeatingEquipment not referenced in RulesetModelInstance

### ISSUE THREAD

**Issue by jugonzal07** [open229/ruleset-model-report-schema#86]
https://github.com/open229/ruleset-model-report-schema/blob/9225628ca63b864488ce6749e5b6fa187faf2e7f/docs229/ASHRAE229.schema.json#L3814

I could not find references to `ServiceWaterHeatingEquipment` under the `RulesetModelInstance` hierachy. The `ASHRAE229connection.pdf` seems to imply it should be referenced by a `ServiceWaterHeatingDistributionSystem` object but I can't seem to make that connection.

**Comment by weilixu** [comment]
https://github.com/open229/ruleset-model-report-schema/blob/master/docs229/ASHRAE229.schema.json#L3833-L3836
Here is likely the connection between `ServiceWaterHeatingEquipment ` and `ServiceWaterHeatingDistributionSystem`. 

Regardless, the `ServiceWaterHeatingEquipment` seems missing its connection to a parent. In PDF, it seems to be on the same level as ASHRAE229.

**Comment by JasonGlazer** [comment]
In RulesetModelInstance, you can reference those in service_water_heating_distribution_systems data element.

**Comment by JasonGlazer** [comment]
Thanks. @jugonzal07 and @weilixu I am adding for 0.0.11 in the RulesetModelInstance data group a data element called  service_water_heating_equipment that provides a list of ServiceWaterHeatingEquipment data groups to be referenced. Each is organized by which ServiceWaterHeatingDistributionSystem they are referencing.
