### ISSUE TITLE
Redundant attributes for HeatRejection data group

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#90]
HeatRejection data group has the following attributes that appear redundant to the attributes included in the FluidLoopDesignAndControl data group. 

These fields are listed below for HeatRejection/FluidLoopDesignAndControl:
reset_type / temperature_reset_type
minimum_reset_temperature / outdoor_high_for_loop_supply_temperature_reset, outdoor_low_for_loop_supply_temperature_reset
design_supply_temperature / design_supply_temperature

Suggest removing these fields from HeatRejection data group.

**Comment by JasonGlazer** [comment]
Addressed in schema 0.0.12 update
