### ISSUE TITLE
Remove input for pump.minimumm_flow?

### ISSUE THREAD

**Issue by supriyagoel** [open229/ruleset-model-report-schema#91]
There are 2 inputs for fluid loop that mean the same thing-

1. fluidloopdesignandcontrol.minimum_flow_fraction
2. pump.minimum_flow

Would it make sense to remove the input at the pump level and only keep the input at the Fluid loop level?

@mkarpman @xingcx

**Comment by JasonGlazer** [comment]
Addressed in 0.0.12
